"""Add missing tables

Revision ID: 8460d13d3a71
Revises: debafcd77709
Create Date: 2026-08-20 22:20:04.130143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8460d13d3a71'
down_revision: Union[str, Sequence[str], None] = 'debafcd77709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('status', sa.String(), nullable=False))
    op.add_column('applications', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('programs', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('programs', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('programs', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'capacity')
    op.drop_column('programs', 'end_date')
    op.drop_column('programs', 'start_date')
    op.drop_column('events', 'capacity')
    op.drop_column('applications', 'admin_notes')
    op.drop_column('applications', 'status')
    # ### end Alembic commands ###
